### ISSUE TITLE
the tensor size is incorrect

### ISSUE THREAD

**Issue by sawbtte** [Bitbol-Lab/DiffPALM#1]
hi,I am trying to run your example code recently;but I found that the tensor ndim you input into msa_transfomer is 4,but the valid input in msa_transformer is ndim=3
![image](https://github.com/Bitbol-Lab/DiffPALM/assets/37359051/0d832167-3d90-42f6-bbe7-12d7ad536359)
is there something I missed?
I will appreciate your help;

**Comment by psridiyer** [comment]
I am also hitting the same problem.  For easy access to the problem description I have enclosed a colab that produces the error.

**Comment by ulupo** [comment]
Hi @sawbtte and @psridiyer!  Bizarrely, I was not notified about this issue (or the other one opened later).  So, sorry for the really delayed reply.  Just to check: did you install the `fair-esm` fork from the Bitbol-Lab organization?  It differs from the official `fair-esm` library precisely so as to take 4-dimensional tensor input. Normally, this fork should be installed automatically when running `pip install -e .`, as per the following line in `settings.ini`:

https://github.com/Bitbol-Lab/DiffPALM/blob/60a2083865d20ac7f5fa1cb73a172fbd2020310e/settings.ini#L42C1-L42C94

You can make sure you have the expected installation by running
```bash
python -m pip uninstall fair-esm
python -m pip install fair-esm@git+https://github.com/Bitbol-Lab/esm.git@oh_input#egg=fair-esm
```

**Comment by ulupo** [comment]
Closing as it seems solved using my considerations above.  Feel free to reopen if still problematic!
